replicaCount: 1

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

containerPort: 80

hpa:
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 75
  targetMemoryUtilizationPercentage: 80

